### ISSUE TITLE
Invalid entity property type. class java.lang.Object

### ISSUE THREAD

**Issue by odwrotnie** [fwbrasil/activate#160]
There is a problem with one Entity:

```
case class TagAttributeValue(m: Model,
                             a: Attribute,
                             val value: List[Tag])
  extends AttributeValue[List[Tag]](m, a)
```

where:

```
abstract class AttributeValue[T](val model: Model,
                                 val attribute: Attribute)
  extends Entity { ... }
```

```
ERROR - Failed to Boot! Your application may not run properly
java.lang.ExceptionInInitializerError: null
    at bootstrap.liftweb.Boot.boot(Boot.scala:106) ~[classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_11]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_11]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
    at net.liftweb.util.ClassHelpers$$anonfun$createInvoker$1.apply(ClassHelpers.scala:364) ~[lift-util_2.10-2.6-M3.jar:2.6-M3]
    at net.liftweb.util.ClassHelpers$$anonfun$createInvoker$1.apply(ClassHelpers.scala:362) ~[lift-util_2.10-2.6-M3.jar:2.6-M3]
    at net.liftweb.http.DefaultBootstrap$$anonfun$boot$1.apply(LiftRules.scala:2036) ~[lift-webkit_2.10-2.6-M3.jar:2.6-M3]
    at net.liftweb.http.DefaultBootstrap$$anonfun$boot$1.apply(LiftRules.scala:2036) ~[lift-webkit_2.10-2.6-M3.jar:2.6-M3]
    at net.liftweb.common.Full.map(Box.scala:610) ~[lift-common_2.10-2.6-M3.jar:2.6-M3]
    at net.liftweb.http.DefaultBootstrap$.boot(LiftRules.scala:2036) ~[lift-webkit_2.10-2.6-M3.jar:2.6-M3]
    at net.liftweb.http.provider.HTTPProvider$class.bootLift(HTTPProvider.scala:88) ~[lift-webkit_2.10-2.6-M3.jar:2.6-M3]
    at net.liftweb.http.LiftFilter.bootLift(LiftServlet.scala:928) [lift-webkit_2.10-2.6-M3.jar:2.6-M3]
    at net.liftweb.http.provider.servlet.ServletFilterProvider$class.init(ServletFilterProvider.scala:40) [lift-webkit_2.10-2.6-M3.jar:2.6-M3]
    at net.liftweb.http.LiftFilter.init(LiftServlet.scala:928) [lift-webkit_2.10-2.6-M3.jar:2.6-M3]
    at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:137) [jetty-servlet-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:810) [jetty-servlet-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:288) [jetty-servlet-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1346) [jetty-webapp-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:743) [jetty-server-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:491) [jetty-webapp-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:117) [jetty-util-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:99) [jetty-util-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) [jetty-server-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:154) [jetty-server-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:117) [jetty-util-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.server.Server.start(Server.java:355) [jetty-server-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:99) [jetty-util-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) [jetty-server-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.server.Server.doStart(Server.java:324) [jetty-server-9.1.0.v20131115.jar:9.1.0.v20131115]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.1.0.v20131115.jar:9.1.0.v20131115]
    at com.earldouglas.xsbtwebplugin.Jetty9Runner.start(Jetty9Runner.scala:131) [xsbt-web-plugin-0.9.0.jar:0.9.0]
    at com.earldouglas.xsbtwebplugin.Container$$anonfun$containerSettings$9.apply(Container.scala:68) [xsbt-web-plugin-0.9.0.jar:0.9.0]
    at com.earldouglas.xsbtwebplugin.Container$$anonfun$containerSettings$9.apply(Container.scala:66) [xsbt-web-plugin-0.9.0.jar:0.9.0]
    at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35) [scala-library.jar:0.13.5]
    at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34) [scala-library.jar:0.13.5]
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47) [scala-library.jar:0.13.5]
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42) [collections-0.13.2.jar:0.13.2]
    at sbt.std.Transform$$anon$4.work(System.scala:64) [task-system-0.13.2.jar:0.13.2]
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237) [tasks-0.13.2.jar:0.13.2]
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237) [tasks-0.13.2.jar:0.13.2]
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18) [control-0.13.2.jar:0.13.2]
    at sbt.Execute.work(Execute.scala:244) [tasks-0.13.2.jar:0.13.2]
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237) [tasks-0.13.2.jar:0.13.2]
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237) [tasks-0.13.2.jar:0.13.2]
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160) [tasks-0.13.2.jar:0.13.2]
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30) [tasks-0.13.2.jar:0.13.2]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_11]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_11]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_11]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_11]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_11]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]
Caused by: java.lang.IllegalStateException: Invalid entity property type. class java.lang.Object
    at net.fwbrasil.activate.entity.EntityValue$$anonfun$tvalFunction$1.apply(EntityValue.scala:206) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at net.fwbrasil.activate.entity.EntityValue$$anonfun$tvalFunction$1.apply(EntityValue.scala:206) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at scala.Option.getOrElse(Option.scala:120) ~[scala-library-2.10.4.jar:na]
    at net.fwbrasil.activate.entity.EntityValue$.tvalFunction(EntityValue.scala:206) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at net.fwbrasil.activate.migration.Migration$$anonfun$15.apply(Migration.scala:301) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at net.fwbrasil.activate.migration.Migration$$anonfun$15.apply(Migration.scala:300) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library-2.10.4.jar:na]
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
    at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library-2.10.4.jar:na]
    at net.fwbrasil.activate.migration.Migration.net$fwbrasil$activate$migration$Migration$$createTableForEntityMetadata(Migration.scala:300) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at net.fwbrasil.activate.migration.Migration$$anonfun$createTableForAllEntities$1.apply(Migration.scala:247) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at net.fwbrasil.activate.migration.Migration$$anonfun$createTableForAllEntities$1.apply(Migration.scala:247) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library-2.10.4.jar:na]
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
    at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library-2.10.4.jar:na]
    at net.fwbrasil.activate.migration.Migration.createTableForAllEntities(Migration.scala:247) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at model.InitialMigration.up(SContext.scala:66) ~[classes/:na]
    at net.fwbrasil.activate.migration.Migration.upActions(Migration.scala:206) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at net.fwbrasil.activate.migration.Migration$$anonfun$7.apply(Migration.scala:116) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at net.fwbrasil.activate.migration.Migration$$anonfun$7.apply(Migration.scala:116) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library-2.10.4.jar:na]
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
    at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library-2.10.4.jar:na]
    at net.fwbrasil.activate.migration.Migration$.actionsOnInterval(Migration.scala:116) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at net.fwbrasil.activate.migration.Migration$.updateTo(Migration.scala:90) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at net.fwbrasil.activate.migration.Migration$.update(Migration.scala:86) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at net.fwbrasil.activate.migration.MigrationContext$class.runMigration(MigrationContext.scala:15) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at model.SContext$.runMigration(SContext.scala:18) ~[classes/:na]
    at net.fwbrasil.activate.migration.MigrationContext$class.runStartupMigration(MigrationContext.scala:26) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at model.SContext$.runStartupMigration(SContext.scala:18) ~[classes/:na]
    at net.fwbrasil.activate.migration.MigrationContext$class.delayedInit(MigrationContext.scala:19) ~[activate-core_2.10-1.6.2.jar:1.6.2]
    at model.SContext$.delayedInit(SContext.scala:18) ~[classes/:na]
    at model.SContext$.<init>(SContext.scala:19) ~[classes/:na]
    at model.SContext$.<clinit>(SContext.scala) ~[classes/:na]
    ... 55 common frames omitted
```

**Comment by fwbrasil** [comment]
@claytonsilva Only immutable lists are supported, the mutable isn't supported. :)

@odwrotnie Does the ```AttributeValue``` class have an attribute that has ```T``` as its type?
