### ISSUE TITLE
Issue when entity classes extend traits referencing one another

### ISSUE THREAD

**Issue by benoitlouy** [fwbrasil/activate#163]
I have 2 traits:

```scala
trait User {
  val name: String
}

trait Business {
  val name: String
  val owner: User
}
```

I then create 2 entity classes extending these traits:

```scala
@InternalAlias("User")
class ActivateUser(val name: String) extends User with Entity

@InternalAlias("Business")
class ActivateBusiness(val name: String, val owner: ActivateUser) extends Business with Entity
```

When initializing my application, the following exception is sometimes thrown:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at issue.activate.SimpleMain$.delayedEndpoint$issue$activate$SimpleMain$1(SimpleMain.scala:7)
	at issue.activate.SimpleMain$delayedInit$body.apply(SimpleMain.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at issue.activate.SimpleMain$.main(SimpleMain.scala:6)
	at issue.activate.SimpleMain.main(SimpleMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.IllegalStateException: Invalid entity property type. Business.owner: interface issue.activate.model.User
	at net.fwbrasil.activate.entity.EntityPropertyMetadata$$anonfun$17.apply(EntityPropertyMetadata.scala:99)
	at net.fwbrasil.activate.entity.EntityPropertyMetadata$$anonfun$17.apply(EntityPropertyMetadata.scala:99)
	at scala.Option.getOrElse(Option.scala:120)
	at net.fwbrasil.activate.entity.EntityPropertyMetadata.<init>(EntityPropertyMetadata.scala:99)
	at net.fwbrasil.activate.entity.EntityMetadata$$anonfun$6.apply(EntityMetadata.scala:39)
	at net.fwbrasil.activate.entity.EntityMetadata$$anonfun$6.apply(EntityMetadata.scala:38)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at net.fwbrasil.activate.entity.EntityMetadata.<init>(EntityMetadata.scala:38)
	at net.fwbrasil.activate.entity.EntityHelper$$anonfun$initialize$1.apply(EntityHelper.scala:47)
	at net.fwbrasil.activate.entity.EntityHelper$$anonfun$initialize$1.apply(EntityHelper.scala:43)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at net.fwbrasil.activate.entity.EntityHelper$.initialize(EntityHelper.scala:43)
	at net.fwbrasil.activate.entity.id.EntityIdContext$class.$init$(EntityId.scala:109)
	at issue.activate.context$.<init>(context.scala:6)
	at issue.activate.context$.<clinit>(context.scala)
	... 16 more
```

I have committed the entire project to reproduce the issue there: https://github.com/benoitlouy/activate_issue

The exception is not always thrown and the application runs fine most of the time. But from time to time it will fail.

**Comment by fwbrasil** [comment]
@benoitlouy Please reopen if the @evaldobratti didn't work.
